name: Crear Check
  on:[push,pull_request]

  jobs:
    crear-check:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout del codigo
          uses: actions/checkout@v2

        - name: Crear Check Run
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            curl -L -X POST \
            -H "Accept: application/vnd.github+json"

            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{github.repository }}/check-runs \
            -d '{
              "name": "Mi Check",
              "head_sha": "${{ github.event.pull_request.head.sha}}",
              "status": "in_progress",
              "output": {
                "title": "Resumen del Check",
                "summary": "Este es un resumen de mi check."
              }
            }'